keybindings:
  back: q
  next_page: ctrl-d
  previous_page: ctrl-u
  jump_to_start: ctrl-a
  jump_to_end: ctrl-e
  jump_to_album: a
  jump_to_artist_album: A
  jump_to_context: o
  manage_devices: d
  decrease_volume: '-'
  increase_volume: +
  toggle_playback: space
  seek_backwards: <
  seek_forwards: '>'
  next_track: n
  previous_track: p
  help: '?'
  shuffle: ctrl-s
  repeat: ctrl-r
  search: /
  submit: enter
  copy_song_url: c
  copy_album_url: C
  audio_analysis: v
  basic_view: B
  add_item_to_queue: z
  open_settings: ctrl-,
  save_settings: alt-s
behavior:
  seek_milliseconds: 5000
  volume_increment: 10
  volume_percent: 100
  tick_rate_milliseconds: 16
  enable_text_emphasis: true
  show_loading_indicator: true
  enforce_wide_search_bar: false
  enable_global_song_count: true
  enable_discord_rpc: true
  discord_rpc_client_id: null
  shuffle_enabled: false
  liked_icon: â™¥
  shuffle_icon: ğŸ”€
  repeat_track_icon: ğŸ”‚
  repeat_context_icon: ğŸ”
  playing_icon: â–¶
  paused_icon: â¸
  set_window_title: true
  visualizer_style: Equalizer
theme:
  active: 0, 180, 180
  banner: 0, 200, 200
  error_border: 200, 0, 0
  error_text: 255, 100, 100
  hint: 200, 200, 0
  hovered: 180, 0, 180
  inactive: 128, 128, 128
  playbar_background: Reset
  playbar_progress: 0, 200, 200
  playbar_progress_text: 255, 255, 255
  playbar_text: Reset
  selected: 0, 200, 200
  text: Reset
  background: Reset
  header: Reset
  highlighted_lyrics: 0, 200, 200
